# Generated by Django 4.0.5 on 2022-06-18 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('dest_Division_Id', models.AutoField(primary_key=True, serialize=False)),
                ('division_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Destinations_States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(max_length=30)),
                ('destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Destinations.destinations')),
            ],
        ),
    ]
