# Generated by Django 4.0.5 on 2022-06-18 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0002_remove_destinations_states_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations_states',
            old_name='destinations',
            new_name='destination',
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('states_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Destinations.destinations_states')),
            ],
        ),
    ]
