# Generated by Django 4.0.5 on 2022-06-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0003_rename_destinations_destinations_states_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_Title', models.TextField()),
            ],
        ),
    ]
