# Generated by Django 4.0.5 on 2022-06-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0004_discriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_Title', models.CharField(max_length=100)),
                ('Discription', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Destinations.cities')),
                ('dest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Destinations.destinations')),
                ('dest_stat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Destinations.destinations_states')),
            ],
        ),
        migrations.DeleteModel(
            name='Discriptions',
        ),
    ]
